### ISSUE TITLE
Link Issue when editing

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1158] opened 2024-07-30 18:51 UTC
I'm not sure if it's meant to work this way, but I keep highlighting a link to edit it and I'll highlight it (not click on it) and will be taken to the link I've highlighted. When I'm editing a page, this is easy to rectify because I can just go back and keep working (after making sure what I just did didn't get lost - sometimes it does and sometimes it doesn't). When I'm editing or working in a block, this takes me out of the block and I lose everything I just did.

**Comment by timurtripp** [comment] 2024-08-21 17:31
Haven't been able to determine what's causing this behavior, only that none of our plugins seem to be the culprit and holding down alt/option when clicking the link prevents following it. Possibly a bug with the link plugin itself.

**Comment by timurtripp** [comment] 2024-08-21 17:59
It's being caused by one of the numerous junk tracking scripts that Google Analytics is adding. Disabling this in the Google Tag contrib module fixes the problem. GA is horrible and maybe I can finally argue for getting rid of it...

**Comment by timurtripp** [comment] 2024-09-25 22:12
Resolved via CuBoulder/tiamat10-profile#199 and CuBoulder/tiamat10-profile#204

**Closed by timurtripp** 2024-09-25 22:12 UTC
Labels: bug, editor experience
