### ISSUE TITLE
Space settings not working in section

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/tiamat-theme#1033] opened 2024-06-05 15:29 UTC
I thought there was a ticket for this from a while back, but can't find it so just making sure this is a known issue.

https://live-ucbdev-homepage.pantheonsite.io/academics

There is spacing added to the section with a text block within it:
![Screenshot 2024-06-05 at 9 27 54 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/f604da62-d501-4eed-ab8c-567aa9d78725)

But the text block is going all the way to the left edge:
![Screenshot 2024-06-05 at 9 25 51 AM](https://github.com/CuBoulder/tiamat-theme/assets/1757082/35504c66-8782-487f-8dfe-87a6c4733c47)

**Comment by patrickbrown-io** [comment] 2024-06-06 18:07
Text block in an edge to edge section

**Comment by jnicholCU** [comment] 2024-06-11 21:27
This is a duplicate of #802

**Closed** 2024-06-12 16:15 UTC
Labels: change, duplicate
