### ISSUE TITLE
Related Articles on Migrated Sites

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1242] opened 2024-08-22 16:47 UTC
There's a few issues we're seeing with related articles on migrated sites.

Migrated sites with articles are displaying the related articles at the bottom of the page even though the article is not set to display them. (https://live-ucbprod-lab-betterton.pantheonsite.io/2022/06/12/toward-task-capable-active-matter-learning-avoid-clogging-confined-collectives-collisions)
<img width="445" alt="image" src="https://github.com/user-attachments/assets/f411be53-af8e-4641-b81f-6a80b5c6bef9">

The element has no heading so it's not clear what these are
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/200c6250-9def-4fa9-b888-47e2bd55128e">

The related articles aren't the most recent.
On https://live-ucbprod-lab-betterton.pantheonsite.io/2022/06/12/toward-task-capable-active-matter-learning-avoid-clogging-confined-collectives-collisions the articles are from 2017, 2016, and 2006, but on a test list I made (https://live-ucbprod-lab-betterton.pantheonsite.io/test-list) there's at least 10 articles that should've been included that were skipped.

Articles aren't even related
On https://www.colorado.edu/aerospace, some of the articles just have the same three articles displaying but they don't even have anything in common.
https://www.colorado.edu/aerospace/2024/07/15/designing-autonomous-robots-use-mars-and-closer-home
https://www.colorado.edu/aerospace/2024/07/02/students-earn-third-nasa-lunar-competition
https://www.colorado.edu/aerospace/2024/07/03/scheeres-joins-esas-hera-asteroid-mission

I'm still unclear on how if someone wants to add or remove this functionality that they are able to do it **without** having to edit each article one by one. There only seems to be a way to set that new articles will have it added by default.  New sites may not want to add something like this until they have more article content, making it difficult to add to each article, and a site with a lot of articles will have difficulty removing it should they not want that to display anymore.

**Comment by patrickbrown-io** [comment] 2024-08-22 16:57
Duplicate of https://github.com/CuBoulder/migrate_express/issues/54

**Comment by patrickbrown-io** [comment] 2024-08-22 17:10
> Migrated sites with articles are displaying the related articles at the bottom of the page even though the article is not set to display them

Migration issue see https://github.com/CuBoulder/migrate_express/issues/54, adding the paragraph will fix this behavior

> Related Articles aren't most recent or relevent

Check component ranking functionality for relatedness. See if API pulls most recent first or check if async calls like `Article Aggregator Blocks` throwing off the order.

> I'm still unclear on how if someone wants to add or remove this functionality...

Global on/off? Need to discuss, potentially separate issue

**Comment by jcsparks** [comment] 2024-08-22 17:24
@timurtripp  - does that apply retroactively to previously created articles?   The help text for the setting says it will apply to "new" articles.

**Closed** 2024-09-04 19:25 UTC
Labels: bug, duplicate
