### ISSUE TITLE
Preview image link results in a 500 error

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/tiamat-theme#1445] opened 2024-11-04 21:01 UTC
If you click on the preview link when editing an image in the media library, you get a not very helpful error message:

"Oops, something went wrong. Check your browser's developer console for more details."

The js console shows:

An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /admin/focal_point/preview/111/50x50?focal_point_token=OVHDPKMeM6C4yv22xC28iQWB7AdaDWWdiSxD9qs02cw
StatusText: error
ResponseText: The website encountered an unexpected error. Try again later.

And the Drupal error log shows:

Error: Call to a member function getDefinitions() on null in Drupal\focal_point\Controller\FocalPointPreviewController->getFocalPointImageStyles() (line 244 of /code/web/modules/contrib/focal_point/src/Controller/FocalPointPreviewController.php).

#0 /code/web/modules/contrib/focal_point/src/Controller/FocalPointPreviewController.php(113): Drupal\focal_point\Controller\FocalPointPreviewController->getFocalPointImageStyles()
#1 [internal function]: Drupal\focal_point\Controller\FocalPointPreviewController->content('111', '50x50')
#2 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#3 /code/web/core/lib/Drupal/Core/Render/Renderer.php(627): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#4 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#5 /code/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#6 /code/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#7 /code/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /code/web/modules/custom/ucb_admin_menus/src/Middleware/Redirect403.php(47): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /code/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\ucb_admin_menus\Middleware\Redirect403->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /code/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /code/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /code/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /code/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /code/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /code/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /code/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /code/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 {main}

**Comment by jnicholCU** [comment] 2024-11-11 02:03
This is a known issue and a duplicate of issue #1322 
There is a patch that has been reviewed and tested that looks to be the fix but it hasn't been merged into the Focal Point mainstream yet.

**Comment by jnicholCU** [comment] 2024-11-11 02:04
The issue in the module can be found here: https://www.drupal.org/project/focal_point/issues/3462165

**Comment by patrickbrown-io** [comment] 2024-11-19 20:24
This should be fixed now via https://www.drupal.org/project/focal_point/issues/3462165#comment-15859395
Seems to be working on test containers -- will be in the next update. Holding off on closing for now until after testing

**Comment by jnicholCU** [comment] 2024-11-25 00:42
Looks like this is all working in the newest updates. Closing out the related tickets.

**Closed by jnicholCU** 2024-11-25 00:42 UTC
Labels: bug, duplicate
